// Code generated by entc, DO NOT EDIT.

package ent

import "github.com/facebook/ent/dialect"

func (c *UserClient) Debug() *UserClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &UserClient{config: cfg}
}
